### ISSUE TITLE
Avoid duplicate data when I have multiple cdc-rust enabled

### ISSUE THREAD

**Issue by dragon-D** [scylladb/scylla-cdc-rust#119]
How to avoid repeated consumption of the same data if multiple cdc-rusts are started to monitor the same table

**Comment by piodul** [comment]
I assume this is about splitting consumption across multiple machines. This is currently not supported by the library, but possible to add with moderate (?) amount of effort.

We should probably base it off the design used in scylla-cdc-java.
cc: @avelanarius

**Comment by dragon-D** [comment]
Does the Cdc itself support multiple consumer competition?

**Comment by piodul** [comment]
CDC writes information about changes into multiple streams and each of the streams can be queried separately. Currently, the library learns about the set of all streams, groups them and spawns a separate consumer for each group. So, you could say that the library already divides the work across multiple cores on the same machine.

It is possible to divide this work across multiple machines, however some care needs to be taken to synchronize the worker machines when the topology of the ScyllaDB cluster changes. This is something that the library could do, but does not support at the moment.

If you are curious you can take a look at the "[CDC Streams](https://opensource.docs.scylladb.com/stable/using-scylla/cdc/cdc-streams.html)" and "[Querying CDC Streams](https://opensource.docs.scylladb.com/stable/using-scylla/cdc/cdc-querying-streams.html)" sections of our CDC documentation to learn how it works underneath.

**Comment by dragon-D** [comment]
thx
