### ISSUE TITLE
Update the library to use recent driver version

### ISSUE THREAD

**Issue by wprzytula** [scylladb/scylla-cdc-rust#124]
As shown in a Slack discussion, there indeed is some interest in this library among the community. Let's update the driver's version in the library, so that those who are interested can utilise its full potential.

**Comment by DanielHe4rt** [comment]
Here it goes! @wprzytula  @piodul  
#125

**Comment by piodul** [comment]
https://github.com/scylladb/scylla-cdc-rust/pull/125 was merged, so I'll go ahead and will close this issue.

**Comment by piodul** [comment]
I suppose I should release a new version of this library to really consider this issue done. Reopening.

**Comment by piodul** [comment]
Released as v0.2.0: https://github.com/scylladb/scylla-cdc-rust/releases/tag/v0.2.0
Closing.
